import sqlalchemy as sa
from alembic import op

revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions_chain",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("reward_xp", sa.Integer(), nullable=False),
        sa.Column("reward_mana", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_missions_chain_name"),
    )
    op.create_table(
        "missions_chain_missions",
        sa.Column("mission_chain_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["mission_chain_id"], ["missions_chain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mission_id"], ["missions_mission.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "mission_chain_id", "mission_id", name="pk_missions_chain_missions"
        ),
    )
    op.create_table(
        "missions_dependency",
        sa.Column("mission_chain_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("prerequisite_mission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["mission_chain_id"], ["missions_chain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mission_id"], ["missions_mission.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prerequisite_mission_id"], ["missions_mission.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "mission_chain_id",
            "mission_id",
            "prerequisite_mission_id",
            name="pk_missions_dependency",
        ),
    )
    op.drop_table("missions_dependencies")
    op.add_column("missions_mission", sa.Column("mission_chain_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_missions_mission_mission_chain_id",
        "missions_mission",
        "missions_chain",
        ["mission_chain_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_missions_mission_mission_chain_id", "missions_mission", type_="foreignkey"
    )
    op.drop_column("missions_mission", "mission_chain_id")
    op.create_table(
        "missions_dependencies",
        sa.Column("mission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("prerequisite_mission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions_mission.id"],
            name=op.f("missions_dependencies_mission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_mission_id"],
            ["missions_mission.id"],
            name=op.f("missions_dependencies_prerequisite_mission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "mission_id", "prerequisite_mission_id", name=op.f("pk_missions_dependencies")
        ),
    )
    op.drop_table("missions_dependency")
    op.drop_table("missions_chain_missions")
    op.drop_table("missions_chain")
    # ### end Alembic commands ###
