import sqlalchemy as sa
from alembic import op

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_missions_mission_mission_chain_id", "missions_mission", type_="foreignkey"
    )
    op.drop_column("missions_mission", "mission_chain_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "missions_mission",
        sa.Column("mission_chain_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fk_missions_mission_mission_chain_id",
        "missions_mission",
        "missions_chain",
        ["mission_chain_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
