from alembic import op
from sqlalchemy import text

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        text(
            """
            INSERT INTO ranks_rank (name, required_xp)
            VALUES ('Искатель', 0)
            ON CONFLICT (name) DO NOTHING
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DELETE FROM ranks_rank WHERE name = 'Искатель'"))
    # ### end Alembic commands ###
