import sqlalchemy as sa
from alembic import op

revision = "0023"
down_revision = "0022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_competencies",
        sa.Column("user_login", sa.String(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies_competency.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_login"], ["users_user.login"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_login", "competency_id", name="pk_users_competencies"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_competencies")
    # ### end Alembic commands ###
