"""add_user_mission_approval_table

Revision ID: 0026
Revises: 0025
Create Date: 2024-12-19 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0026"
down_revision = "0025"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_missions_approval",
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("user_login", sa.String(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["mission_id"], ["missions_mission.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_login"], ["users_user.login"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("mission_id", "user_login", name="pk_users_missions_approval"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_missions_approval")
    # ### end Alembic commands ###
