name: Build & Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    strategy:
      matrix:
        action: [ lint, types, tests ]
    steps:
      - name: checkout
        uses: actions/checkout@v4  # actions/checkout@master
      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"
          python-version: 3.13

      - name: run linters
        run: make lint
        continue-on-error: true

      - name: run type checking
        run: make types
        continue-on-error: true

      - name: run tests
        run: make tests-coverage
        continue-on-error: false

  push_to_registry:
    name: Push to Docker registry
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:latest
        continue-on-error: false
